services:
  db:
    image: postgres:15-alpine
    container_name: m13_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: m13_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
